name: sync to s3 and submit
on:
  push:

env:
  GH_TOKEN: secrets.GH_TOKEN

jobs:
  sync:
    name: sync
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'sync')
    steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ldb-hackathon-team-6
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'dataset'      # optional: defaults to entire repository  test:
          DEST_DIR: repo/$GITHUB_SHA/
  submit:
     name: submit
     runs-on: ubuntu-latest
     if: contains(github.event.head_commit.message, 'submit')
     needs: sync
     steps:
       - name: curl
         uses: indiesdev/curl@v1.1
         with:
             # The target URL
             # Required: true if custom-config is not set
             url: https://api.github.com/repos/iterative/ldb-hackathon/actions/workflows/submission.yml/dispatches

             # The request method, basically it's one of GET|POST|PUT|PATCH
             # Default is GET
             method: "POST"

             # List of response status codes to be accepted, else it will set the job to be failed
             # If more than one value is needed, you can use comma(,) as seperator
             # In this case if the response status code is not one of 200, 201 and 204, the job will be failed
             # Default is 200,201,204
             accept: 200,201,204

             # Headers can be passed through json object string
             headers: '{ "Accept": "application/vnd.github+json", "Authorization": "token $GH_TOKEN" }'

             # Params can be passed through json object string
             params: '{ "param1": "value", "param2": "value2" }'

             # Body request
             # Apply only to POST|PUT request
             body: '{"ref":"main","inputs":{"data":"s3://ldb-hackathon-team-6/repo/$GITHUB_SHA","desc":"$GITHUB_SHA"}}'

             # Request timeout (millisec)
             # Default: 1000
             timeout: 1000
